project_name: go-template-project-rendered
version: 2

builds:
  # Linux-only builds (for .deb/.rpm/.apk packages and raw binaries)
  - id: go-template-project-rendered-linux
    binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    goamd64: v1
    main: ./
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Windows + macOS builds (for raw binaries)
  - id: go-template-project-rendered-cross
    binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos: [windows, darwin]
    goarch: [amd64, arm64]
    goamd64: v1
    main: ./
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  # Raw binaries for all platforms (one file per OS/Arch, uncompressed)
  - id: raw-binaries
    ids: [go-template-project-rendered-linux, go-template-project-rendered-cross]
    formats: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

nfpms:
  - id: pkg
    ids: [go-template-project-rendered-linux]
    package_name: go-template-project-rendered
    vendor: "abgoyal"
    homepage: "https://github.com/abgoyal/go-template-project-rendered"
    maintainer: "abgoyal <abgoyal@gmail.com>"
    description: "go-template-project-rendered"
    license: "MIT"
    formats: [deb, rpm, apk]
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/{{ .PackageName }}/LICENSE
        type: file
    deb:
      signature:
        key_file: "{{ .Env.DEB_KEY_FILE }}"
    rpm:
      signature:
        key_file: "{{ .Env.RPM_KEY_FILE }}"
    apk:
      signature:
        key_file: "{{ .Env.APK_KEY_FILE }}"
        key_name: "{{ .Env.APK_KEY_NAME }}"
    overrides:
      deb:
        scripts:
          postinstall: "{{ .Env.DEB_POSTINSTALL_PATH }}"
      rpm:
        scripts:
          postinstall: "{{ .Env.RPM_POSTINSTALL_PATH }}"
        arch: >-
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{- end }}
      apk:
        arch: >-
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{- end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
