name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write

jobs:
  release:
    uses: abgoyal/go-release-pipeline/.github/workflows/pipeline.yml@main
    with:
      releaser_repo: abgoyal/go-release-pipeline
      goreleaser-config-path: .goreleaser.yml
      enable-deb: true
      enable-rpm: true
      enable-apk: true
      deb-postinstall-path: .github/scripts/postinstall.deb.sh
      rpm-postinstall-path: .github/scripts/postinstall.rpm.sh
    secrets: inherit # This securely passes required secrets to the reusable workflow

