name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write

env:
  RELEASER_REPO: abgoyal/go-release-pipeline

jobs:
  release:
    uses: ${{ env.RELEASER_REPO }}/.github/workflows/pipeline.yml@main
    with:
      releaser_repo: ${{ env.RELEASER_REPO }}
      goreleaser-config-path: .goreleaser.yml
      enable-deb: true
      enable-rpm: true
      enable-apk: true
      deb-postinstall-path: .github/scripts/postinstall.deb.sh
      rpm-postinstall-path: .github/scripts/postinstall.rpm.sh
    secrets: inherit # This securely passes required secrets to the reusable workflow

